version: '3'
services:
  cassandra:
    image: "cassandra"
  app:
    build:
      context: .
      args:
        JAR_FILE: /spring-data-cassandra-docker-1.0.0.jar
    restart: always
    ports:
       - "8082:8082"

