spring:
  data:
    cassandra:
      port: 9042
      contact-points: mycassandra
      keyspace-name: asignatura
      schema-action: create_if_not_exists
      entity-base-package: com.example.demo.model